name: CI

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  apk:
    name: Generate APK
    runs-on: macos-latest
    steps:
      - name: install qt static
        uses: orestonce/install-qt@main
        with:
          version: "Qt5.15.14-macOS-Universal-AppleClang15.0.0-noFramework-20240527"
          
      - name: echo something
        run: |
            qmake -h
            mingw32-make