name: Build OpenCC v1.1.9 with Doxygen on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      OPENCC_VERSION: ver.1.1.9
      DOXYGEN_DIR: D:\doxygen  # 非系统盘目录，避免权限问题
      DOXYGEN_EXE: D:\doxygen\bin\doxygen.exe

    steps:
      - name: Checkout OpenCC v1.1.9
        uses: actions/checkout@v4
        with:
          repository: BYVoid/OpenCC
          ref: ver.1.1.9
          path: OpenCC
          fetch-depth: 0

      - name: Install Doxygen 1.9.6
        run: |
          # 创建安装目录（非系统盘）
          New-Item -ItemType Directory -Path $env:DOXYGEN_DIR | Out-Null
          
          # 下载官方安装包（通过镜像源避免 404）
          Invoke-WebRequest -Uri "https://github.com/paebbels/doxygen-windows-installer/releases/download/v1.9.6/doxygen-1.9.6-setup.exe" -OutFile "doxygen-setup.exe" -UseBasicParsing
          
          # 静默安装到指定目录
          Start-Process -FilePath "doxygen-setup.exe" -ArgumentList "/S", "/D=$env:DOXYGEN_DIR" -Wait -NoNewWindow
          
          # 验证安装
          if (-not (Test-Path $env:DOXYGEN_EXE)) {
              Write-Error "Doxygen 安装失败"
              exit 1
          }
          & "$env:DOXYGEN_EXE" --version  # 应输出版本号 1.9.6

      - name: Install Build Tools
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
          refreshenv  # 刷新环境变量

      - name: Configure CMake
        working-directory: OpenCC
        run: |
          cmake -B build `
            -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_DOCUMENTATION=ON `
            -DDOXYGEN_EXECUTABLE="$env:DOXYGEN_EXE" `  # 硬编码绝对路径
            -DCMAKE_POLICY_DEFAULT_CMP0074=NEW `      # 启用 CMP0074 策略
            -Wno-dev  # 忽略开发警告

      - name: Build OpenCC
        working-directory: OpenCC
        run: cmake --build build --config Release

      - name: Verify Output
        run: |
          if (-not (Test-Path "build/bin/opencc.exe")) {
              Write-Error "编译失败：未找到 opencc.exe"
              exit 1
          }
          if (-not (Test-Path "build/doc/html/index.html")) {
              Write-Error "文档生成失败"
              exit 1
          }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opencc-windows-v1.1.9
          path: |
            build/bin/*.exe
            build/doc/html/**/*
          retention-days: 30
