name: Build OpenCC with Doxygen on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOXYGEN_BIN: C:\Program Files\doxygen\bin  # Doxygen 可执行文件所在目录

    steps:
      - name: Checkout latest release
        uses: actions/checkout@v4
        with:
          repository: BYVoid/OpenCC
          path: OpenCC
          ref: "ver.1.1.9"  # 获取最新发布标签
          fetch-depth: 0  # 获取完整的版本历史，确保能检出标签

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
          choco install doxygen.install -y --params "/DoxygenInstallDir=$env:DOXYGEN_BIN/.."
          
          # 验证 Doxygen 安装
          $doxygen_exe = Join-Path -Path $env:DOXYGEN_BIN -ChildPath "doxygen.exe"
          & $doxygen_exe --version

      - name: Configure build
        working-directory: OpenCC
        run: |
          cmake -B build `
            -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_DOCUMENTATION=ON `
            -DDOXYGEN_EXECUTABLE=$env:DOXYGEN_BIN\doxygen.exe

      - name: Build OpenCC
        working-directory: OpenCC
        run: |
          cmake --build build --config Release
          # 显示编译后的文件列表，便于调试
          Get-ChildItem -Path build/bin -Recurse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opencc-windows-binaries-docs
          path: |
            OpenCC/build/bin/*.exe
            OpenCC/build/doc/html/**/*
          retention-days: 30
