name: CI

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  apk:
    name: Generate APK
    runs-on: windows-latest
    steps:
      - name: install qt static
        uses: orestonce/install-qt@v0.1.６
        with:
            version: Qt5.6.3-Windows-x86-MinGW4.9.4-staticFull-20200104
      - name: echo something
        run: |
            qmake -h
            mingw32-make