name: Build OpenCC with Doxygen on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOXYGEN_ROOT: C:\Program Files\doxygen
      DOXYGEN_BIN: C:\Program Files\doxygen\bin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: BYVoid/OpenCC
          path: OpenCC

      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install ninja -y
          
          # 安装 Doxygen 并指定安装目录
          choco install doxygen.install -y --params "/DoxygenInstallDir:$env:DOXYGEN_ROOT"
          
          # 手动将 Doxygen 添加到当前会话的 PATH
          $env:PATH = "$env:DOXYGEN_BIN;$env:PATH"
          
          # 验证 Doxygen 安装
          Write-Host "Doxygen 路径验证:"
          Test-Path "$env:DOXYGEN_BIN\doxygen.exe"
          
          # 输出调试信息
          Write-Host "当前 PATH 环境变量:"
          $env:PATH -split ';' | Where-Object { $_ -like '*doxygen*' }

      - name: Verify Doxygen installation
        run: |
          # 直接使用完整路径调用 Doxygen
          & "$env:DOXYGEN_BIN\doxygen.exe" --version
          
          # 验证命令是否可用
          try {
              Get-Command doxygen -ErrorAction Stop
              Write-Host "Doxygen 命令已成功识别"
          } catch {
              Write-Host "警告: doxygen 命令未在 PATH 中找到，但将使用完整路径" -ForegroundColor Yellow
          }

      - name: Configure build
        working-directory: OpenCC
        run: |
          cmake -B build `
            -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_DOCUMENTATION=ON `
            -DDOXYGEN_EXECUTABLE="$env:DOXYGEN_BIN\doxygen.exe" `
            -DCMAKE_VERBOSE_MAKEFILE=ON

      - name: Build OpenCC
        working-directory: OpenCC
        run: cmake --build build --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opencc-windows-binaries-docs
          path: |
            OpenCC/build/bin/*.exe
            OpenCC/build/doc/html/**/*
          retention-days: 30
