name: CI

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  apk:
    name: Generate APK
    runs-on: windows-latest
    steps:
      - name: build m3u8d
        if: runner.os == 'windows'
        run: |
          git clone https://github.com/BYVoid/OpenCC
          cd OpenCC
          build.cmd
          dir
