name: Build OpenCC v1.1.9 with Doxygen on Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      OPENCC_VERSION: ver.1.1.9
      DOXYGEN_ROOT: C:\Program Files\doxygen
      DOXYGEN_EXECUTABLE: C:\Program Files\doxygen\bin\doxygen.exe
      SYSTEM_BIN_DIR: C:\Windows\System32  # 已在PATH中的系统目录

    steps:
      - name: Checkout specific version
        uses: actions/checkout@v4
        with:
          repository: BYVoid/OpenCC
          path: OpenCC
          ref: ${{ env.OPENCC_VERSION }}
          fetch-depth: 0

      - name: Install dependencies
        run: |
          choco install cmake ninja -y
          
          # 使用 Chocolatey 安装 Doxygen
          choco install doxygen.install -y --params "/DoxygenInstallDir:$env:DOXYGEN_ROOT"
          
          # 验证 Doxygen 安装
          if (-not (Test-Path "$env:DOXYGEN_EXECUTABLE")) {
              Write-Error "Doxygen 可执行文件不存在: $env:DOXYGEN_EXECUTABLE"
              exit 1
          }
          
          # 关键修复：将 doxygen.exe 复制到已在 PATH 中的目录
          Copy-Item -Path "$env:DOXYGEN_EXECUTABLE" -Destination "$env:SYSTEM_BIN_DIR" -Force
          
          # 验证系统路径是否可访问 doxygen
          Get-Command doxygen -ErrorAction Stop
          
          # 输出版本信息
          doxygen --version

      - name: Configure build
        working-directory: OpenCC
        run: |
          cmake -B build `
            -G "Ninja" `
            -DCMAKE_BUILD_TYPE=Release `
            -DBUILD_DOCUMENTATION=ON `
            -DDOXYGEN_EXECUTABLE=doxygen `  # 直接使用命令名，无需路径
            -DCMAKE_VERBOSE_MAKEFILE=ON `
            -Wno-dev

      - name: Build OpenCC
        working-directory: OpenCC
        run: |
          cmake --build build --config Release
          
          # 验证编译结果
          $exe_path = "build/bin/opencc.exe"
          if (-not (Test-Path $exe_path)) {
              Write-Error "编译失败: 未找到 opencc.exe"
              exit 1
          }
          
          # 显示编译后的文件列表
          Get-ChildItem -Path build/bin -Recurse

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: opencc-windows-v1.1.9
          path: |
            OpenCC/build/bin/*.exe
            OpenCC/build/doc/html/**/*
          retention-days: 30
