name: CI

# Controls when the workflow will run
on: push
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  apk:
    name: Generate APK
    runs-on: windows-latest
    steps:
      - name: install qt static
        uses: orestonce/install-qt@dev
        with:
          version: "Qt4.8.7-Windows-x86-MinGW4.9.4-20200104"