# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on: 
  release:
    types: [ created ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: build
        run: |
          git clone https://github.com/andydotxyz/sshterm
          cd sshterm
          go mod tidy
          go build -ldflags -H=windowsgui
          ls
      - name: upload release windows_amd64
        uses: Guerra24/upload-to-release@v1
        with:
          name: sshterm_windows_amd64-${{ github.ref_name }}.exe
          path: sshterm/sshterm.exe
          repo-token: ${{ secrets.GITHUB_TOKEN }}    
